workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Configurar Proyecto
        script: | 
          cd $(find . -name "pubspec.yaml" -exec dirname {} \;)
          flutter pub get
      - name: Build APK
        script: | 
          cd $(find . -name "pubspec.yaml" -exec dirname {} \;)
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"
