workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Force Gradle 8.0 (INDISPENSABLE)
        script: |
          cd android
          mkdir -p gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK Rapido (Solo ARM64)
        script: |
          # Sin ofuscación y solo para móviles modernos para máxima velocidad
          flutter build apk --release --target-platform android-arm64
    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"
